[package]
name = "structr-derive"
version = "0.1.0"
authors = ["metarmask <ihvarfner@gmail.com>"]
edition = "2018"

[dependencies]
# syn = "1.0"
syn = { version=">=1.0.58", features = ["parsing", "extra-traits", "full"] }
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true